**Dataset**
labeled datasset collected from twitter (Lab 1 - Hate Speech.tsv)

**Objective**
classify tweets containing hate speech from other tweets. <br>
0 -> no hate speech <br>
1 -> contains hate speech <br>

**Total Estimated Time = 90-120 Mins**

**Evaluation metric**
macro f1 score

### Import used libraries

In [98]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
import nltk
from nltk.corpus import stopwords
import seaborn as sns
import matplotlib.pyplot as plt
import re
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_colwidth', 500)
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [99]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Load Dataset

###### Note: search how to load the data from tsv file

In [100]:
df = pd.read_csv("/content/drive/MyDrive/Lab_1_Hate_Speech.tsv.zip", sep= "\t")
df.head(100)

,id,label,tweet
0,1,0,@user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction. #run
1,2,0,@user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx. #disapointed #getthanked
2,3,0,bihday your majesty
3,4,0,#model i love u take with u all the time in urð±!!! ðððð ð¦ð¦ð¦
4,5,0,factsguide: society now #motivation
5,6,0,[2/2] huge fan fare and big talking before they leave. chaos and pay disputes when they get there. #allshowandnogo
6,7,0,@user camping tomorrow @user @user @user @user @user @user @user dannyâ¦
7,8,0,the next school year is the year for exams.ð¯ can't think about that ð­ #school #exams #hate #imagine #actorslife #revolutionschool #girl
8,9,0,we won!!! love the land!!! #allin #cavs #champions #cleveland #clevelandcavaliers â¦
9,10,0,@user @user welcome here ! i'm it's so #gr8 !
10,11,0,â #ireland consumer price index (mom) climbed from previous 0.2% to 0.5% in may #blog #silver #gold #forex
11,12,0,we are so selfish. #orlando #standwithorlando #pulseshooting #orlandoshooting #biggerproblems #selfish #heabreaking #values #love #
12,13,0,i get to see my daddy today!! #80days #gettingfed
13,14,1,@user #cnn calls #michigan middle school 'build the wall' chant '' #tcot
14,15,1,no comment! in #australia #opkillingbay #seashepherd #helpcovedolphins #thecove #helpcovedolphins
15,16,0,ouch...junior is angryð#got7 #junior #yugyoem #omg
16,17,0,i am thankful for having a paner. #thankful #positive
17,18,1,retweet if you agree!
18,19,0,its #friday! ð smiles all around via ig user: @user #cookies make people
19,20,0,"as we all know, essential oils are not made of chemicals."
20,21,0,#euro2016 people blaming ha for conceded goal was it fat rooney who gave away free kick knowing bale can hit them from there.
21,22,0,sad little dude.. #badday #coneofshame #cats #pissed #funny #laughs
22,23,0,product of the day: happy man #wine tool who's it's the #weekend? time to open up &amp; drink up!
23,24,1,@user @user lumpy says i am a . prove it lumpy.
24,25,0,@user #tgif #ff to my #gamedev #indiedev #indiegamedev #squad! @user @user @user @user @user
25,26,0,beautiful sign by vendor 80 for $45.00!! #upsideofflorida #shopalyssas #love
26,27,0,@user all #smiles when #media is !! ðð #pressconference in #antalya #turkey ! sunday #throwback love! ððâ¤ï¸
27,28,0,we had a great panel on the mediatization of the public service #ica16
28,29,0,happy father's day @user ðððð
29,30,0,50 people went to nightclub to have a good night and 1 man's actions means those people are lost to their families forever #rip#orlando
30,31,0,i have never had a chance to vote for a presidential candidate i was excited about and this cycle looks to be no different.
31,32,0,#alohafriday #time does #not #exist #positivevibes #hawaiian @user @user @user @user
32,33,0,"@user rip to the fellow nohern ireland fan who sadley passed away tonight!.. gawa, forever singing and cheering on fire"
33,34,0,it was a hard monday due to cloudy weather. disabling oxygen production for today. #goodnight #badmonday
34,35,1,it's unbelievable that in the 21st century we'd need something like this. again. #neverump #xenophobia
35,36,0,#taylorswift1989 bull up: you will dominate your bull and you will direct it whatever you want it to do. w
36,37,0,morning~~ #travelingram #dalat #ripinkylife
37,38,0,@user once more only one word tells it all: #photoshop. #enoughisenough #dontphotoshopeverything #wheresallthenaturalphotos
38,39,0,"oh, #cedarpoint. waited 2 hours in the valravn line and it stopped working. we were so close."
39,40,0,i am thankful for sunshine. #thankful #positive
40,41,0,when you finally finish a book you've been working on for awhile... #bookworm #ontothenextnovel
41,42,0,"yup, being a knicks fan is hard, so its easier to just be an nba fan when the playoffs roll around ð"
42,43,0,there is life after social networking. embrace each day. be
43,44,0,my mom shares the same bihday as @user bihday snake! see you this weekend ðð¼
44,45,0,lovely echeveria blooms#flowers #grow #gardening #iphonesia #bliss #blooms #basilicabotanica
45,46,0,i am amazing. #i_am #positive #affirmation
46,47,0,#model i love u take with u all the time in urð±!!! ðððð ð¦ð¦ð¦
47,48,0,#whenever im and #something goes #wrong |
48,49,0,feeling blue #illustration
49,50,0,the best pa about life is knowing who you are! ðâï¸ð¼ð» â¦
50,51,0,#abc2020 getting ready 2 remove the victums frm #pulseclub #prayfororlando
51,52,0,for her #bihday we got her a #nose #job @user ðð¶ððð #bihday #petunia we love you ð
52,53,0,off to concelebrate at the #albanpilgrimage for the first time. @user
53,54,0,@user let the scum-baggery begin.....
54,55,0,"thank you! ðð super love it! â¤ï¸ zpamdelacruz #wedding# @ dolores, capas tarlac."
55,56,0,a scourge on those playing baroque pieces on piano beyond belief
56,57,1,@user lets fight against #love #peace
57,58,0,"happy fatherâs day, mr. rayos #video #fathers #day #rayos #world #hotvideo #videos"
58,59,0,@user ascot times with this babe â¤ï¸â¤ï¸ #ascot #fashion #monochrome #style #instahappyday
59,60,0,the weekend..is here!!ððððð #selfie #yolo #xoxo #like4like
60,61,0,happy at work conference: right' mindset leads to culture-of-development organizations #work #mindset
61,62,0,christina grimmie's last performance before being shot... via @user #christinarip #voice #christinagrimmie
62,63,0,we are ready to dance #roar #preschoolers #students #proudâ¦
63,64,0,you've really hu my feelings :(
64,65,0,@user my wife whom i adore had to miss your poland show because she had surgery. her name is bridget &amp; she's my everything.
65,66,0,@user i am so jealous of you right now.... #chatiado
66,67,0,i celebrate every man that has played it's fatherly role. father's day#
67,68,0,i'm sure they are just as happy.... ðð½ðð½ðð½ hour
68,69,1,ð©the white establishment can't have blk folx running around loving themselves and promoting our greatness
69,70,0,good morning! the journey begins! ððð»ð³ #travel #yeah #thejourneybegins #helloâ¦
70,71,0,@user # if you #luv #hottweets like this from â¶ â¥#venusexchangeâ¥
71,72,0,our new brochures have arrived! how exciting!! #aworks #solutions
72,73,0,so much stuff happening in florida! first #orlando shooting and now #disneygatorattack on a two year old kidð¥ð
73,74,0,"@user ferrari will do itðªð¼ for the sake of the championship. this gp is clearly a turning point rb, ferrari,mercs...ð"
74,75,0,aced my first test! #proud
75,76,0,"seeks probe into #udtapunjab' leak, points finger at #amarinder, #aap"
76,77,0,@user wrapping up #senseaboutmaths @user 6th @user @user @user
77,78,1,"@user hey, white people: you can call people 'white' by @user #race #identity #medâ¦"
78,79,0,@user @user you might be. just have not shown here today. regurgitated talking points and name calling?
79,80,0,sometimes you have to raise a few brows to raise the bar. #golfstrengthandconditioning #strong #felixfoisgolf
80,81,0,about that ððð #greathonour #careerconvos @user @user
81,82,0,@user designing #innovative learning space @user to include #wateringhole #cave #mountaintop #campfire @user hâ¦
82,83,1,how the #altright uses &amp; insecurity to lure men into #whitesupremacy
83,84,0,carrying a gun wouldn't of helped if you can't take it in with you. gun control won't stop the black market! terrorism will get worse!
84,85,0,use the power of your mind to #heal your body!! - #altwaystoheal #healthy #peace!
85,86,0,woohoo!! just over 5 weeks to go!
86,87,0,being in a far away place where you have no family members hus
87,88,0,"ready to rehearse tonight with new music and new videos, look out for the announcement! #midweek #newmusic #watchthisspace #guitar"
88,89,0,now on monday nights at 8pm on #up channel!!!! i finally get to see what all the fuss is about!!!
89,90,0,watching the new episodes of @user on @user
90,91,0,@user offline now after a very nice and long night.. ð #snapchat @user #redhead #vermillionred
91,92,0,15 things incredibly #people do
92,93,0,yes! received my acceptance letter for my masters so will be back at @user again in october! #goodtimes #history
93,94,0,"daughter riding her bike around driveway, son playing his guitar for us while we enjoy ðº by the campfire... #summeime #memories"
94,95,0,omg!!! loving this station!!! way to jam out at work!!! while getting work done of course!!!! #memories @user
95,96,0,"@user i'll always hope that one day i'll get to hug you, but i don't think that it's gonna happen anytime soon..."
96,97,0,#model i love u take with u all the time in urð±!!! ðððð ð¦ð¦ð¦
97,98,0,couple having sex fat naked japanese girls
98,99,0,"#hump on that #hump day #humpersð© @ edwardsville, pennsylvania"
99,100,0,personalised we... gbp 7.99 get here: #shop #cool #home #fun

### Data splitting

It is a good practice to split the data before EDA helps maintain the integrity of the machine learning process, prevents data leakage, simulates real-world scenarios more accurately, and ensures reliable model performance evaluation on unseen data.

In [101]:
df['label'].value_counts()
#unsampling

label
0    29322
1     2213
Name: count, dtype: int64

In [102]:
X=df['tweet']
y=df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

### EDA on training data

- check NaNs

In [103]:
df.isna().sum()

id       0
label    0
tweet    0
dtype: int64

- check duplicates

In [104]:
df.duplicated().sum()

np.int64(0)

- show a representative sample of data texts to find out required preprocessing steps

In [105]:
df.sample(10)

,id,label,tweet
25863,26291,0,bday to all fathers!! .. we loved you all
30072,30500,0,2 days until graduation #gettingserious #almosthere #countdown #proud #happy then senior week worry begins ð¬ð¬ð¬ð¬
13165,13471,0,our next show is monday at the fiddler's elbow in camden. it's looking like it's going to be a huge night!
20216,20627,0,"taking my parents to see @user tonight,i'm nervous as it's the 1st time i'm leaving my 4 month old son at home ð¥ð©ð­ #coldplaywembley"
3563,3678,0,@user nova and the pursuit of healthy immune system.
30679,31107,0,hanging me upside down ð¤ð #upsidedown #smiles #couple #boyfriend #girlfriend #playingâ¦
21209,21620,0,@user expected live tweets during @user from @user but as long as he's okay i'm good. #loveislove
10280,10417,0,"yooo this bitch needs therapy, dique ""i still want you"" get tf outta here you still need this foot up ya ass ð¯ð smdh"
25243,25671,0,just received a txt to state my bihday celebrations are staing a week early #â¤suprises @user #tophubby long weekend tooð
2619,2661,0,"this #weekend #go far whatever #makes #you , #we are #here to #take #care of #your #laundry. #call..."

In [106]:
df['tweet'].head(5)

0                         @user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run
1    @user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx.    #disapointed #getthanked
2                                                                                                           bihday your majesty
3                                          #model   i love u take with u all the time in urð±!!! ðððð
ð¦ð¦ð¦
4                                                                                        factsguide: society now    #motivation
Name: tweet, dtype: object

- check dataset balancing

In [107]:
df['label'].value_counts()

label
0    29322
1     2213
Name: count, dtype: int64

In [108]:
df['tweet'].head(10)

0                                              @user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run
1                         @user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx.    #disapointed #getthanked
2                                                                                                                                bihday your majesty
3                                                               #model   i love u take with u all the time in urð±!!! ðððð
ð¦ð¦ð¦
4                                                                                                             factsguide: society now    #motivation
5                                 [2/2] huge fan fare and big talking before they leave. chaos and pay disputes when they get there. #allshowandnogo
6                                                                          @user camping tomorrow @user @user @user @user @user @user @user dannyâ¦
7    the next school year is the year for exams.ð¯ can't think about that ð­ #school #exams   #hate #imagine #actorslife #revolutionschool #girl
8                                                             we won!!! love the land!!! #allin #cavs #champions #cleveland #clevelandcavaliers  â¦
9                                                                                                   @user @user welcome here !  i'm   it's so #gr8 !
Name: tweet, dtype: object

- Cleaning and Preprocessing are:
    - 1
    - 2
    - 3
    - ... etc.

### Cleaning and Preprocessing

#### Extra: use custom scikit-learn Transformers

Using custom transformers in scikit-learn provides flexibility, reusability, and control over the data transformation process, allowing you to seamlessly integrate with scikit-learn's pipelines, enabling you to combine multiple preprocessing steps and modeling into a single workflow. This makes your code more modular, readable, and easier to maintain.

##### link: https://www.andrewvillazon.com/custom-scikit-learn-transformers/

#### Example usage:

In [109]:
from sklearn.base import BaseEstimator, TransformerMixin
import re

class CustomTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
      self.lemmatizer = WordNetLemmatizer()
      self.stop_words = set(stopwords.words('english'))


    def fit(self, X, y=None):
        # Add code for fitting the transformer here
        return self

    def _process_text(self, text):

        #convert small charachters
        text=str(text).lower()

        #remove tags
        text=re.sub(r"http\S+|www\S+|https\S+|@\w+","",text)

        text = re.sub(r'[^\w\s]', '', text)

        text=re.sub(r'[^a-z\s]','',text)

        words = text.split()


        cleane_words=[
            self.lemmatizer.lemmatize(w)
            for w in words if w not in self.stop_words
        ]



        return " ".join(cleane_words)

    def transform(self, X, y=None):
        if isinstance(X, pd.Series):
            return X.apply(self._process_text)
        else:
            return [self._process_text(t) for t in X]

**You  are doing Great so far!**

### Modelling

#### Extra: use scikit-learn pipline

##### link: https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

Using pipelines in scikit-learn promotes better code organization, reproducibility, and efficiency in machine learning workflows.

#### Example usage:

In [110]:
from sklearn.pipeline import Pipeline

model = LogisticRegression()

# Create the pipeline
pipeline = Pipeline(steps=[
    ('preprocessing', CustomTransformer()),
    ('Vectorizing', CountVectorizer()),
    ('model', model),
])

#Now you can use the pipeline for training and prediction
pipeline.fit(X_train, y_train)
pipeline.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0])

#### Evaluation

**Evaluation metric:**
macro f1 score

Macro F1 score is a useful metric in scenarios where you want to evaluate the overall performance of a multi-class classification model, **particularly when the classes are imbalanced**

![Calculation](https://assets-global.website-files.com/5d7b77b063a9066d83e1209c/639c3d934e82c1195cdf3c60_macro-f1.webp)

In [111]:
y_pred = pipeline.predict(X_test)
f1_score(y_test, y_pred, average='macro')

0.8155193460447956

In [112]:
test_tweet = ["I am so anger today! #blessed"]
pipeline.predict(test_tweet)

array([0])

### Enhancement

- Using different N-grams
- Using different text representation technique
- Hyperparameter tuning

In [113]:
params={
    "Vectorizing__ngram_range" :[(1,1),(1,2)],
    "Vectorizing__max_features" :[5000,10000],

    'model__C': [0.1, 1, 10],
    'model__penalty': ['l2'],
    'model__solver': ['liblinear']
}

In [114]:
pipeline = Pipeline(steps=[
    ('preprocessing', CustomTransformer()),
    ('Vectorizing', TfidfVectorizer()),
    ('model', model),
])

In [115]:
grid_search = GridSearchCV(pipeline, params, cv=5, scoring='f1_macro')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing', CustomTransformer()),
                                       ('Vectorizing', TfidfVectorizer()),
                                       ('model', LogisticRegression())]),
             param_grid={'Vectorizing__max_features': [5000, 10000],
                         'Vectorizing__ngram_range': [(1, 1), (1, 2)],
                         'model__C': [0.1, 1, 10], 'model__penalty': ['l2'],
                         'model__solver': ['liblinear']},
             scoring='f1_macro')

### Conclusion and final results

In [116]:
grid_search.best_params_

{'Vectorizing__max_features': 10000,
 'Vectorizing__ngram_range': (1, 2),
 'model__C': 10,
 'model__penalty': 'l2',
 'model__solver': 'liblinear'}

In [117]:
best_model = grid_search.best_estimator_
y_pred2 = best_model.predict(X_test)
f1_score(y_test, y_pred2, average='macro')

0.8377702913139717

#### Done!